### ISSUE TITLE
undefined method `user_todos_path' for

### ISSUE THREAD

**Issue by t0d0r** [dalyons/redmine-todos-scrum-plugin#7]
Hi, I have the same problem as:

http://www.redmine.org/boards/3/topics/4070#message-9227

ActionView::TemplateError (undefined method `user_todos_path' for #ActionView::Base:0x9706364) on line #11 of to
dos/_new_todo.html.erb:
8: %>
9:
10: <div class="new-todo">
11:   <% remote_form_for [parent_object,todo],
12:       #:todo, todo, :url => {:controller => "todos", :action=> "create", :project_id => todo.project },
13:       #:update =>  TodosController::UL_ID + todo.parent_or_root_id, :position => :bottom,
14:       :success => "elements['todo[text]'].activate().clear();" do |f| %>

I set permissions on directory for same user that run mongrel_cluster and Settings -> Roles and Permissions
- OS is FreeBSD 6.4
- Rails 2.2.2
- Ruby 1.8.7 (2009-04-08 patchlevel 160) 
- Source of the todos_plugins is downloaded via 
  git clone git://github.com/dalyons/redmine-todos-scrum-plugin.git redmine_todos_plugin
  on 29.10.2009

**Comment by giemsky** [comment]
Patch for this:
http://github.com/gmiklaszewski/redmine-todos-scrum-plugin/commit/d97a20ed5257dba246ffb790e0ff6245bef10160

**Comment by dalyons** [comment]
works in redmine 0.9x on rails > 2.3
